### PR TITLE
Upgrade "whatwg-fetch" to 3.0.0

### PR DESCRIPTION
**Pull request by dasa**
**Type:** feature

The following has been addressed in the PR:

* [ ] There is a related issue
* [ ] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Upgrade "whatwg-fetch" to 3.0.0 to get new features:
https://github.com/github/fetch/releases/tag/v3.0.0

Resolves #???

### CODE REVIEW

**Comment by dasa** [comment]
It seems that the 3.0 version can not be loaded in Node. This is why I removed it from `intern.json`. ` tests/i18n/support/util.ts` is now failing in IE 11, but I'm not sure the best way to fix it. Should the `getJson` function conditionally import it?

**Comment by agubler** [comment]
@dasa Could you move the fetch plugin into the the browser specific plugins (and use the umd build)?

```json
"plugins+": [
	"./node_modules/whatwg-fetch/dist/fetch.umd.js",
	{
		"script": "./dist/dev/src/shim/browser.js",
		"useLoader": true
	},
	{
		"script": "./dist/dev/tests/widget-core/support/loadCustomElements.js",
		"useLoader": true
	}
]
```

**Comment by dasa** [comment]
Thanks, the build errors now appear to be the same as the latest on `master`: https://travis-ci.org/dojo/framework/builds/460686944

**Comment by agubler** [comment]
@dasa yup we seem to be experiencing technical difficulties...

**Comment by agubler** [comment]
@dasa Can you rebase off the latest master, hopefully the CI issues are resolved.

**Comment by dasa** [comment]
Tests passed 😄

**Pull request merged**
